[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
clear_msig_anchor = "6trGJ4oFMisx8J4DmvhETz432nBFEgbaoDmANpwCDVui"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
